### PR TITLE
New Stuff

### PR DESCRIPTION
**Pull request by KreativeKngYT**
new lightrail, monorail and 25 toner, and a few track changes

### CODE REVIEW

**Comment by CSX8600** [comment]
There's a number of conflicts that need to be resolved. You likely need to merge `dev` into this branch.

Also for future reference - please always base your changes off of `dev` instead of `main`, and likewise, make your pull requests against `dev` instead of `main`.

**Comment by KreativeKngYT** [comment]
TF did it go to main, when me and RZ were doing this i linked it off Dev, not main

**Comment by CSX8600** [comment]
Idk man - just calling it as I see it. I changed the base of this from `main` to `dev` and that's how I got the conflicts to appear

**Comment by KreativeKngYT** [comment]
delete this

**Pull request closed without merging**
